Repository webserv-blah/webserv, pull requests merged in 2025-02, with the labels that each got.

#1 build: 커밋 메시지 템플릿 변경
  .gitmessage.txt
Labels: build

#2 feat: ClientManager 기본 헤더파일 작성
  src/clientManager/Makefile
  src/clientManager/clientManager.cpp
  src/clientManager/clientManager.hpp
  src/subsrc1/Makefile
  src/subsrc1/subsrc1.cpp
  src/subsrc1/subsrc1.hpp
  src/subsrc2/subsrc2.cpp
  src/subsrc2/subsrc2.hpp
Labels: feat

#4 Revert "feat: ClientManager 기본 헤더파일 작성 (#2)"
  .gitignore
  src/Makefile
  src/clientManager/clientManager.cpp
  src/clientManager/clientManager.hpp
  src/subsrc1/Makefile
  src/subsrc1/subsrc1.cpp
  src/subsrc1/subsrc1.hpp
  src/subsrc2/Makefile
  src/subsrc2/subsrc2.cpp
  src/subsrc2/subsrc2.hpp
Labels: fix

#21 feat: TimeoutHandler 객체 구현
  src/TimeoutHandler/Makefile
  src/TimeoutHandler/TimeoutHandler.cpp
  src/TimeoutHandler/TimeoutHandler.hpp
Labels: feat

#22 Feat/configuration GlobalConfig, ConfigParser 객체 구현
  config.txt
  src/ConfigParser/ConfigParser.cpp
  src/ConfigParser/ConfigParser.hpp
  src/ConfigParser/Makefile
  src/ConfigParser/get_next_token.cpp
  src/ConfigParser/parse_location_block.cpp
  src/ConfigParser/parse_server_block.cpp
  src/ConfigParser/parse_simple_directives.cpp
  src/ConfigParser/utilities.cpp
  src/ConfigParser/utilities.hpp
  src/GlobalConfig/GlobalConfig.cpp
  src/GlobalConfig/GlobalConfig.hpp
  src/GlobalConfig/Makefile
  src/GlobalConfig/Optional.hpp
  src/Makefile
  src/main.cpp
  src/subsrc1/subsrc1.cpp
  src/subsrc1/subsrc1.hpp
  src/subsrc2/subsrc2.cpp
  src/subsrc2/subsrc2.hpp
  src/subsrc2/subsrc22.hpp
Labels: feat

#28 feat: StaticHandler
  src/RequestHandler/Makefile
  src/RequestHandler/StaticHandler.cpp
  src/RequestHandler/StaticHandler.hpp
Labels: feat

#37 feat: RequestParser 객체 구현
  src/Makefile
  src/RequestMessage/RequestMessage.cpp
  src/RequestMessage/RequestMessage.hpp
  src/RequestParser/Makefile
  src/RequestParser/RequestParser.cpp
  src/RequestParser/RequestParser.hpp
  src/utils/utils.cpp
  src/utils/utils.hpp
Labels: feat

#40 feat: findRequestConfig() 구현
  src/ConfigParser/ConfigParser.cpp
  src/ConfigParser/ConfigParser.hpp
  src/ConfigParser/parse_simple_directives.cpp
  src/GlobalConfig/GlobalConfig.cpp
  src/GlobalConfig/GlobalConfig.hpp
Labels: feat

#43 feat: fileUtilites 네임스페이스 구현
  src/RequestHandler/file_utils.cpp
  src/RequestHandler/file_utils.hpp
Labels: feat

#50 feat: ResponseBuilder 객체 초안
  src/ResponseBuilder/ErrorPageResolver.cpp
  src/ResponseBuilder/ErrorPageResolver.hpp
  src/ResponseBuilder/Makefile
  src/ResponseBuilder/ResponseBuilder.cpp
  src/ResponseBuilder/ResponseBuilder.hpp
Labels: build

#64 feat: StaticHandler autoindex
  src/RequestHandler/Makefile
  src/RequestHandler/StaticHandler.cpp
  src/RequestHandler/StaticHandler.hpp
  src/utils/Makefile
  src/utils/file_utils.cpp
  src/utils/file_utils.hpp
Labels: feat

#70 main브랜치에 존재한 Request 테스트, test브랜치로 분리
  Makefile
  _request_msg_test.sh
  src/main.cpp
  src/readRequest.cpp
  src/real_main.cpp
Labels: etc

#67 feat: sendResponse
  src/EventHandler/EventHandler.hpp
  src/EventHandler/EventHandlerSendResponse.cpp
Labels: HTTPResponse

#72 feat: RequestParser 정상화, 고도화 및 예외 처리 강화
  src/ClientSession/ClientSession.cpp
  src/ClientSession/ClientSession.hpp
  src/RequestMessage/RequestMessage.cpp
  src/RequestMessage/RequestMessage.hpp
  src/RequestParser/RequestParser.cpp
  src/RequestParser/RequestParser.hpp
  src/utils/utils.cpp
  src/utils/utils.hpp
Labels: HTTPRequest

#79 feat: 기존 readRequest 함수 추가 및 이름 변경
  src/EventHandler/EventHandler.cpp
  src/EventHandler/EventHandler.hpp
  src/EventHandler/EventHandlerReadRequest.cpp
  src/EventHandler/EventHandlerRecvRequest.cpp
Labels: HTTPRequest

#87 refactor: 인클루드 가드 변경
  src/ClientSession/ClientSession.hpp
  src/ConfigParser/ConfigParser.hpp
  src/Demultiplexer/DemultiplexerBase.hpp
  src/Demultiplexer/KqueueDemultiplexer.hpp
  src/EventHandler/EventHandler.hpp
  src/GlobalConfig/GlobalConfig.hpp
  src/RequestHandler/StaticHandler.hpp
  src/RequestMessage/RequestMessage.hpp
  src/RequestParser/RequestParser.hpp
  src/ResponseBuilder/ErrorPageResolver.hpp
  src/ResponseBuilder/ResponseBuilder.hpp
  src/ServerManager/ServerManager.hpp
  src/TimeoutHandler/TimeoutHandler.hpp
  src/include/commonEnums.hpp
  src/utils/Optional.hpp
  src/utils/file_utils.hpp
  src/utils/utils.hpp
Labels: etc

#99 feat: RequestParser 요청 에러시 사용하는 EnumSesStatus 변경 및 에러 처리방법 변경
  src/ClientSession/ClientSession.cpp
  src/ClientSession/ClientSession.hpp
  src/EventHandler/EventHandlerRecvRequest.cpp
  src/RequestParser/RequestParser.cpp
  src/RequestParser/RequestParser.hpp
  src/include/commonEnums.hpp
Labels: HTTPRequest

#115 feat: RequestParser 파싱과정에 GlobalConfig 사용 로직 추가
  src/ClientSession/ClientSession.cpp
  src/ClientSession/ClientSession.hpp
  src/RequestParser/RequestParser.cpp
  src/RequestParser/RequestParser.hpp
Labels: HTTPRequest

#125 build: 컴파일시 보이는 make log 정리
  Makefile
  include_make/Color.mk
  include_make/Link.mk
  include_make/Recipe_src.mk
  include_make/Recipe_subsrc.mk
  include_make/Variable.mk
  include_make/Verbose.mk
  src/ClientManager/Makefile
  src/ClientSession/Makefile
  src/ConfigParser/Makefile
  src/Demultiplexer/Makefile
  src/EventHandler/Makefile
  src/GlobalConfig/Makefile
  src/Makefile
  src/RequestHandler/Makefile
  src/RequestMessage/Makefile
  src/RequestParser/Makefile
  src/ResponseBuilder/Makefile
  src/ServerManager/Makefile
  src/TimeoutHandler/Makefile
  src/utils/Makefile
Labels: etc

#129 fix: file_utils namespace scope 수정 및 string.back() 제거
  src/utils/file_utils.cpp
Labels: etc

#130 Refactor: eventhandler
  src/ClientManager/ClientManager.cpp
  src/ClientManager/ClientManager.hpp
  src/ClientSession/ClientSession.cpp
  src/ClientSession/ClientSession.hpp
  src/EventHandler/EventHandler.cpp
  src/EventHandler/EventHandler.hpp
Labels: SocketProgramming

#131 Refactor/event loop
  src/EventHandler/EventHandler.cpp
  src/ServerManager/ServerManager.hpp
  src/ServerManager/ServerManagerRun.cpp
Labels: SocketProgramming, I/Omultiplexing

#135 feat: CgiHandler::isCGI() 로직 수정
  src/EventHandler/EventHandler.cpp
  src/RequestHandler/CgiHandler.cpp
  src/RequestHandler/CgiHandler.hpp
Labels: CGI

#136 feat: PHP CGI 예제 스크립트 및 사용 가이드 추가
  README_CGI.md
  config_example.conf
  html/cgi-bin/form.php
  html/cgi-bin/hello.php
  html/cgi-bin/info.php
  html/index.html
Labels: CGI

#138 feat: 기본 에러 페이지 템플릿 구현
  html/error/default_error.html
  src/ResponseBuilder/ErrorPageResolver.cpp
  src/ResponseBuilder/ErrorPageResolver.hpp
Labels: HTTPResponse

#137 feat: static_handler
  src/RequestHandler/StaticHandler.cpp
  src/RequestHandler/StaticHandler.hpp
Labels: HTTPResponse

#140 refactor: RequestParser 최적화 및 버그 수정
  src/ClientSession/ClientSession.cpp
  src/ClientSession/ClientSession.hpp
  src/EventHandler/EventHandlerRecvRequest.cpp
  src/Makefile
  src/RequestMessage/RequestMessage.cpp
  src/RequestMessage/RequestMessage.hpp
  src/RequestParser/RequestParser.cpp
  src/RequestParser/RequestParser.hpp
  src/include/commonEnums.hpp
Labels: HTTPRequest

#145 refactor: setStatus 제거
  src/EventHandler/EventHandlerSendResponse.cpp
Labels: HTTPResponse

#146 feat: ClientSession reqmsg&config getter 두가지 반환형
  src/ClientSession/ClientSession.cpp
  src/ClientSession/ClientSession.hpp
  src/EventHandler/EventHandlerRecvRequest.cpp
  src/RequestParser/RequestParser.cpp
Labels: etc

#158 fix: RequestParser 헤더필드 단일 처리 로직 변경 및 추가 오류 해결
  src/RequestParser/RequestParser.cpp
  src/RequestParser/RequestParser.hpp
  src/RequestParser/RequestParserBody.cpp
  src/RequestParser/RequestParserFieldLine.cpp
  src/RequestParser/RequestParserStartLine.cpp
Labels: HTTPRequest

#164 feat: ClientSessio의 Config pointer NULL 안정성 보장
  src/EventHandler/EventHandlerRecvRequest.cpp
Labels: HTTPRequest

#172 refactor: reqConfig, reqMsg 접근방법 수정
  src/ClientSession/ClientSession.cpp
  src/ClientSession/ClientSession.hpp
  src/EventHandler/EventHandler.cpp
  src/EventHandler/EventHandlerRecvRequest.cpp
  src/RequestHandler/CgiHandler.cpp
  src/RequestParser/RequestParser.cpp
Labels: HTTPRequest, HTTPResponse, Configuration

#171 refactor: findRequestConfig 개선
  src/GlobalConfig/GlobalConfig.cpp
Labels: Configuration

#174 build: Makefile 로그 단순화한 기능 추가 및 기본으로 설정
  include_make/Link.mk
  include_make/Recipe_src.mk
  include_make/Recipe_subsrc.mk
  include_make/Verbose.mk
Labels: etc

#175 fix: cgi_handler
  html/cgi-bin/hello.php
  src/RequestHandler/CgiHandler.cpp
  src/ResponseBuilder/ResponseBuilder.cpp
  src/ResponseBuilder/ResponseBuilder.hpp
  src/utils/file_utils.cpp
  src/utils/file_utils.hpp
  src/utils/utils.cpp
  src/utils/utils.hpp
Labels: CGI

#183 fix: CgiHandler 쿼리문 인식을 위한 isCGI함수 수정, php파일들의 shebang 수정
  html/cgi-bin/form.php
  html/cgi-bin/info.php
  src/RequestHandler/CgiHandler.cpp
Labels: CGI

#184 fix: Idle Timeout과 Request Timeout 구분
  src/ClientSession/ClientSession.cpp
  src/ClientSession/ClientSession.hpp
  src/ServerManager/ServerManagerRun.cpp
  src/TimeoutHandler/TimeoutHandler.cpp
  src/TimeoutHandler/TimeoutHandler.hpp
Labels: SocketProgramming, I/Omultiplexing

#187 refactor: handleRedirection
  src/EventHandler/EventHandler.cpp
  src/EventHandler/EventHandler.hpp
  src/RequestHandler/StaticHandler.cpp
  src/RequestHandler/StaticHandler.hpp
Labels: HTTPRequest, HTTPResponse

#185 Feat: prepare tester
  42tester.conf
  42tester.mk
  Dockerfile
  Makefile
  include_make/Variable.mk
  src/ClientManager/ClientManager.cpp
  src/ConfigParser/parse_simple_directives.cpp
  src/Demultiplexer/DemultiplexerBase.tpp
  src/EventHandler/EventHandler.cpp
  src/EventHandler/EventHandlerRecvRequest.cpp
  src/ServerManager/ServerManagerRun.cpp
  src/include/errorUtils.hpp
  src/utils/examples/README.md
  src/utils/examples/error_handling_example.cpp
  src/utils/file_utils.cpp
  src/utils/file_utils.hpp
  src/utils/utils.cpp
  src/utils/utils.hpp
  var/www/YoupiBanane/Yeah/not_happy.bad_extension
  var/www/YoupiBanane/nop/other.pouic
  var/www/YoupiBanane/nop/youpi.bad_extension
  var/www/YoupiBanane/youpi.bad_extension
  var/www/YoupiBanane/youpi.bla
Labels: etc

#191 build: src/Makefile DIRS 자동인식 및 인클루드 자동인식
  include_make/Variable.mk
  src/Makefile
Labels: etc

#192 docs: 커밋 메시지 가이드라인 업데이트 및 CLAUDE.md 관리 설정
  .gitignore
  .gitmessage.txt
Labels: etc

#193 chore/루트 디렉토리 정리
  Dockerfile
  config/42tester.conf
  config/config.conf
  config/config_example.conf
  config/simple_config.conf
  html/CGI.md
Labels: etc
