Repository webserv-blah/webserv, pull requests merged in 2025-03, with the labels that each got.

#197 feat: 표준화된 에러 로그 출력 시스템
  doc/CGI_README.md
  doc/DEBUG_LOG.md
  doc/ERROR_HANDLING.md
  doc/error_handling_example.cpp
  src/EventHandler/EventHandler.cpp
  src/EventHandler/EventHandlerRecvRequest.cpp
  src/EventHandler/EventHandlerSendResponse.cpp
  src/ServerManager/ServerManager.cpp
  src/ServerManager/ServerManagerRun.cpp
  src/TimeoutHandler/TimeoutHandler.cpp
  src/include/errorUtils.hpp
  src/main.cpp
Labels: etc

#200 fix: 에러 로그 메시지 출력 방식 개선
  include_make/Variable.mk
  src/EventHandler/EventHandler.cpp
  src/EventHandler/EventHandlerRecvRequest.cpp
  src/EventHandler/EventHandlerSendResponse.cpp
  src/include/errorUtils.hpp
  src/main.cpp
  src/utils/utils.cpp
  src/utils/utils.hpp
Labels: etc

#203 feat: 42테스터를 위한 컨테이너 환경 준비
  .gitignore
  42tester.mk
  Dockerfile
  config/42tester.conf
Labels: etc

#213 feat: RequestMessage & Parser에 HEAD 메서드 추가
  src/ConfigParser/ConfigParser.cpp
  src/RequestMessage/RequestMessage.cpp
  src/RequestMessage/RequestMessage.hpp
  src/RequestParser/RequestParserBody.cpp
  src/RequestParser/RequestParserStartLine.cpp
Labels: HTTPRequest

#214 feat: HEAD method 구현
  src/RequestHandler/CgiHandler.cpp
  src/RequestHandler/StaticHandler.cpp
  src/RequestHandler/StaticHandler.hpp
  src/RequestMessage/RequestMessage.hpp
Labels: HTTPResponse

#219 fix: upload_file 디렉토리 경로 / 추가
  src/RequestHandler/StaticHandler.cpp
Labels: HTTPResponse

#221 Chore/response debug log
  src/RequestHandler/CgiHandler.cpp
  src/ResponseBuilder/ResponseBuilder.cpp
Labels: HTTPResponse

#222 fix: isCGI함수에서 확장자 검사 방식 변경 compare -> find
  src/RequestHandler/CgiHandler.cpp
Labels: etc

#224 fix: 설정파일 파서에서 중복된 포트 설정 허용하지 않게 수정
  src/ConfigParser/ConfigParser.cpp
  src/ConfigParser/ConfigParser.hpp
Labels: Configuration

#226 fix: RequestParser에서 findRequestConfig 로직 순서 변경 및 도메인네임 파싱 추가
  src/EventHandler/EventHandlerRecvRequest.cpp
  src/RequestHandler/CgiHandler.cpp
  src/RequestParser/RequestParser.cpp
Labels: etc

#229 fix: POST upload_path 없을시 에러 수정
  config/simple_config.conf
  src/RequestHandler/StaticHandler.cpp
Labels: HTTPResponse

#232 refactor: POST 메소드 파일 업로드 방식 변경
  Dockerfile
  config/simple_config.conf
  html/original.txt
  src/GlobalConfig/GlobalConfig.cpp
  src/RequestHandler/StaticHandler.cpp
  src/RequestHandler/StaticHandler.hpp
Labels: HTTPResponse

#238 refactor: recv, send이후 errno확인 제거, shebang 공통경로로 수정
  html/cgi-bin/form.py
  html/cgi-bin/hello.py
  html/cgi-bin/info.py
  src/EventHandler/EventHandlerRecvRequest.cpp
  src/EventHandler/EventHandlerSendResponse.cpp
Labels: HTTPRequest, I/Omultiplexing, HTTPResponse, etc

#240 refactor: filepath에 '/' 중복 방지
  config/simple_config.conf
  src/RequestHandler/StaticHandler.cpp
  src/ResponseBuilder/ErrorPageResolver.cpp
  src/utils/file_utils.cpp
Labels: HTTPResponse

#245 feat: 아무 메서드도 허용하지 않는 설정 방법 추가
  src/ConfigParser/parse_location_block.cpp
Labels: Configuration

#247 Refactor: 요청이 디렉토리이고 index 지시자가 CGI extension인 경우 CGI 처리, CGI 파일 업로드 스크립트 추가
  config/simple_config.conf
  html/cgi-bin/upload.py
  html/error/404.html
  html/index.html
  html/index2.html
  src/EventHandler/EventHandler.cpp
  src/RequestHandler/CgiHandler.cpp
  src/RequestHandler/CgiHandler.hpp
  src/utils/file_utils.cpp
  src/utils/file_utils.hpp
Labels: HTTPResponse, CGI

#249 fix: 인덱스 파일의 경로을 올바르게 구하도록 수정
  src/ConfigParser/ConfigParser.cpp
  src/ConfigParser/ConfigParser.hpp
  src/ConfigParser/parse_location_block.cpp
  src/GlobalConfig/GlobalConfig.cpp
  src/GlobalConfig/GlobalConfig.hpp
  src/RequestHandler/CgiHandler.cpp
  src/RequestHandler/StaticHandler.cpp
Labels: HTTPRequest, Configuration

#251 refactor: cgi 동작 서브젝트의 요구사항에 맞게 구현
  html/cgi-bin/download.py
  html/cgi-bin/file_downloader.py
  html/cgi-bin/file_reader.py
  html/cgi-bin/file_uploader.py
  html/cgi-bin/upload.py
  html/index.html
  html/index2.html
  html/info.py
  html/uploads/infinity.mp4
  html/uploads/original.txt
  src/RequestHandler/CgiHandler.cpp
  src/RequestHandler/CgiHandler.hpp
  src/ResponseBuilder/ResponseBuilder.cpp
  src/utils/file_utils.cpp
Labels: HTTPResponse, CGI

#259 fix: ResponseBuilder::getReasonPhrase 추가 및 수정
  src/ResponseBuilder/ResponseBuilder.cpp
Labels: HTTPResponse

#260 fix: ErrorPageResolver에도 URI too large 추가
  src/ResponseBuilder/ErrorPageResolver.cpp
  src/ResponseBuilder/ResponseBuilder.cpp
Labels: HTTPResponse

#261 refactor: remove downloader
  html/cgi-bin/download.py
  html/cgi-bin/file_downloader.py
  html/index.html
  html/index2.html
  html/info.py
Labels: CGI

#262 chore: std::find 헤더파일 인클루드 누락
  src/ConfigParser/ConfigParser.hpp
Labels: etc

#263 Refactor/optimize loop
  src/ClientSession/ClientSession.cpp
  src/ClientSession/ClientSession.hpp
  src/EventHandler/EventHandler.cpp
  src/ServerManager/ServerManagerRun.cpp
  src/TimeoutHandler/TimeoutHandler.cpp
Labels: I/Omultiplexing

#271 fix: CGI요청일 때 isMethodAllowed 검사
  src/EventHandler/EventHandler.cpp
  src/EventHandler/EventHandler.hpp
  src/RequestHandler/StaticHandler.cpp
  src/RequestHandler/StaticHandler.hpp
Labels: HTTPRequest

#272 fix: read, send 함수 return 값 -1, 0, 양수 나누어 처리
  src/EventHandler/EventHandlerSendResponse.cpp
  src/RequestHandler/CgiHandler.cpp
Labels: HTTPResponse
